POST http://localhost:3000/posts
Content-Type:application/json

{
    "title":"Demo",
    "slug":"new-post-4",
    "postType":"post",
    "status":"draft",
    "content":"this is dummy hehe",
    "schema":"{\"something\":false, \"hehe\":false}",
    "featuredImageUrl": "http://localhost.com/images/image1.jpg",
    "publishedOn": "2024-03-16T07:46:32+0000",
    "tags":["nestjs","tss"],
    "metaOption":{
        "metaValue":"{\"sidebarEnabled\":false, \"footerActive\":false}"
    },
    "authorId":1
}