POST http://localhost:3000/posts
Content-Type:application/json

{
    "title":"Demo",
    "slug":"new-post",
    "postType":"post",
    "status":"draft",
    "content":"this is dummy",
    "tags":["nestjs","tss"],
    "metaOption":[{"key":"test", "value":"Asdfas"}]
}