PATCH http://localhost:3000/posts
Content-Type:application/json

{
    "id":18,
    "title":"Edited",
    "slug":"new-edit",
    "postType":"post",
    "status":"draft",
    "content":"this is dummy",
    "tags":[1,2]
}