POST http://localhost:3000/posts
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoidGFuemVlbDAxQGdtYWlsLmNvbSIsImlhdCI6MTczMzA4NTY2MCwiZXhwIjoxNzMzMDg5MjYwLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.ApK8cWpD5TSpFHAKCL0F0lEOqlfRC2E8ixirlCiXIS8
{
  "title": "What's new with NestJS",
  "postType": "post",
  "slug": "new-with-nestjs-16",
  "status": "draft",
  "content": "test content",
  "schema": "{\r\n \"@context\": \"https:\/\/schema.org\",\r\n \"@type\": \"Person\"\r\n }",
  "featuredImageUrl": "http://localhost.com/images/image1.jpg",
  "metaOption" : {
      "metaValue": "{\"sidebarEnabled\": true, \"footerActive\":true}"
    },
  "tags": []
}