POST http://localhost:3000/auth/refresh-tokens
Content-Type:application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImlhdCI6MTczMzc3NjEyMywiZXhwIjoxNzMzODYyNTIzLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.YtsQoH4LHgT1wAKWktIDb6KZKkqYEAHWYuWj-VjrmcY"
}